In [14]:
#This file teaches tensor stuff to torch beginners

import torch
import numpy as np

In [16]:
#Defining Tensor

t1 = torch.tensor([1.2,3], dtype=float)
print(t1.dtype)

#You can also define tensor using numpyarray

nparray=np.array([1,2,3])

t2 = torch.tensor(nparray)

#You can also change the type of any tensor
print(t2)
t2=t2.float()
print(t2)



torch.float64
tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


In [17]:
t1

tensor([1.2000, 3.0000], dtype=torch.float64)

In [23]:
#Reshaping

'''Reshaping a tensor involves changing its dimensions while 
keeping the same number of elements. PyTorch provides the view() 
method to reshape tensors.'''

#1. 
x = torch.randn(2, 3)

#x has two rows and three columns

print(x)
x.shape

#means converting x to 2 rows of size 1x3
y = x.view(2, 1, 3)
print(y)

#2. Flattening a tensor:
#You can flatten a tensor into a 1D tensor using view() as follows:
z=y.view(-1)
print(z)
#the -1 automatically calculates the number of dimensions of the flattened vector
z=x.view(-1,2)
print(z)


tensor([[ 1.3227, -1.0865, -0.7728],
        [-1.0376, -0.0453,  0.7973]])
tensor([[[ 1.3227, -1.0865, -0.7728]],

        [[-1.0376, -0.0453,  0.7973]]])
tensor([ 1.3227, -1.0865, -0.7728, -1.0376, -0.0453,  0.7973])
tensor([[ 1.3227, -1.0865],
        [-0.7728, -1.0376],
        [-0.0453,  0.7973]])


In [25]:
x=torch.randn(5,6)

In [26]:
print(x)

tensor([[-0.1395,  0.2871, -1.4482, -0.1060,  0.3064, -0.1653],
        [-1.2679,  0.2323,  0.8126, -1.0802,  1.2016,  0.1483],
        [-1.3711,  0.0568, -1.6733, -0.2379, -0.7399, -1.5309],
        [ 0.8828, -0.0080,  0.8376, -0.4107, -0.4801,  0.0530],
        [-0.4884, -0.5937, -0.5837,  0.1728, -1.1252,  0.2688]])


In [27]:
y=x.view(-1,3)

In [28]:
y.shape

torch.Size([10, 3])

In [21]:
z=x.view(3,2)
print(z)

tensor([[-1.5513,  1.0109],
        [-1.2036, -0.0404],
        [-1.0699,  0.2796]])


In [19]:
x.shape

torch.Size([2, 3])

In [29]:


'''Slicing:  slicing is the operation of selecting a subset of elements from a tensor.
You can use slicing to extract a part of a tensor or modify specific elements of a tensor. '''

#1: Slicing a tensor by indices

x = torch.randn(3, 4)
#y below is a 1-d tensor
y = x[1, :]  #This will give you the second row of the tensor


#2: Slicing a tensor by range:

x = torch.randn(3, 4)
y = x[0:2, :] 


In [31]:
x

tensor([[ 1.9373,  0.8614, -2.4549, -0.8728],
        [-0.1560, -1.1280, -1.3172, -2.0388],
        [ 0.6957,  0.8391,  2.0464, -0.0495]])

In [32]:
y

tensor([[ 1.9373,  0.8614, -2.4549, -0.8728],
        [-0.1560, -1.1280, -1.3172, -2.0388]])

In [34]:

#3: Slicing a tensor by step:

x = torch.randn(3, 4)
y = x[0, 0::2]

#y is a tensor of shape (2,) containing alternate elements of first row of x

#4. Advanced Slicing

x = torch.randn(3, 4)

mask = x > 0  #boolean tensor 

y = x[mask]

print(mask)

print(y)  #a 1-d tensor with only positive elements



tensor([[ True, False, False,  True],
        [ True, False,  True, False],
        [False,  True,  True,  True]])
tensor([0.4175, 0.6229, 0.8779, 0.2339, 1.3101, 1.1087, 0.4315])


In [42]:
#Tensor Concatenation

'''concatenation is the operation of joining two or more tensors 
together along a specified dimension. Concatenation is a useful operation 
for combining data from different sources or 
for increasing the dimensionality of a tensor.'''

#1. Concatenation tensors along existing dimensions

x = torch.randn(3, 4)
y = torch.randn(3, 4)
z = torch.cat((x, y), dim=0)





In [43]:
print(x)
print(y)
print
z.shape

tensor([[-0.1864,  0.4595,  0.1563, -0.9113],
        [ 0.8137, -0.3987, -0.4780,  0.0173],
        [ 0.2140, -1.5190, -1.4712,  0.4424]])
tensor([[ 0.5433,  0.3100, -0.2326, -0.1650],
        [-1.3258, -1.7558,  0.2040, -1.3744],
        [-1.6691,  0.5277,  0.1246,  0.3600]])


torch.Size([6, 4])

In [44]:
#2. Concatenating tensors along a new dimension:

x = torch.randn(3, 4)
y = torch.randn(3, 4)
z = torch.cat((x, y), dim=1)

print(x)
print(y)
print(z)

tensor([[-1.2616, -0.1463,  0.6849,  0.1271],
        [-0.2889,  0.7233, -2.1348,  1.8370],
        [-0.4207,  0.1142, -0.8417,  0.7519]])
tensor([[-0.4684,  1.1775,  0.6036,  0.4022],
        [ 0.5614,  0.5777, -1.2149,  0.6340],
        [-1.3597,  0.0538, -1.0272,  0.0221]])
tensor([[-1.2616, -0.1463,  0.6849,  0.1271, -0.4684,  1.1775,  0.6036,  0.4022],
        [-0.2889,  0.7233, -2.1348,  1.8370,  0.5614,  0.5777, -1.2149,  0.6340],
        [-0.4207,  0.1142, -0.8417,  0.7519, -1.3597,  0.0538, -1.0272,  0.0221]])


In [46]:
#Matrix Multiplication

#1. Element wise multiplications

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = a * b
print(c)

#2. Matrix Multiplication

a = torch.randn(3, 4)
b = torch.randn(4, 5)
c = torch.matmul(a, b)
print(c)


#Batch Multiplication

a = torch.randn(2, 3, 4)
b = torch.randn(2, 4, 5)
c = torch.matmul(a, b)

print(a)
print(b)
print(c)


tensor([ 4, 10, 18])
tensor([[ 0.2091, -0.3291, -2.4816, -0.1843, -0.0290],
        [-2.1631,  0.4818, -5.5041,  0.0273,  1.5353],
        [ 1.8502, -0.0166,  2.5186, -0.2541, -1.7885]])
tensor([[[-0.1460, -0.3374,  0.5117, -0.9058],
         [-0.6190,  0.4468, -2.0836,  0.6849],
         [-0.1385,  0.3256, -1.1819,  0.2690]],

        [[ 1.0203,  0.0816, -1.5661,  1.7030],
         [-1.3553, -0.2862,  0.9757, -0.2892],
         [-1.6667, -1.1893, -3.2392, -0.1509]]])
tensor([[[ 0.0635, -1.0017,  0.9196,  0.7759, -1.0266],
         [ 0.1212,  2.1722, -0.0633,  0.8564, -0.1785],
         [ 0.1923,  0.6317, -0.5731, -2.2511, -0.2364],
         [ 0.6540,  2.1936,  1.9776, -0.2172, -1.0575]],

        [[ 1.7779, -0.5614,  1.5246,  0.6967,  0.8345],
         [-0.6900,  1.0879, -0.9502, -0.3844, -1.1154],
         [-0.5811,  0.6289,  0.3214, -1.3620, -1.9324],
         [-1.2743, -0.6531,  0.7430,  1.2427,  0.0569]]])
tensor([[[-0.5441, -2.2504, -2.1975, -1.3574,  1.0470],
         [ 0.0620, 

In [47]:
c.shape

torch.Size([2, 3, 5])

In [48]:
a.shape

torch.Size([2, 3, 4])

In [49]:
b.shape

torch.Size([2, 4, 5])